---
title: "ProyectoTD2024"
output: html_document
author: "Eric Villaescusa, Isaac Pazmiño, Alexandra Estela, Oscar Ibañez, Adrià Reyes"
date: "2024-03-30"
---

```{r setup, include=FALSE}
#Cargamos las librerias necesarias
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(readr)
library(dplyr)
library(rlist)
```

```{r}
#Cargamos los nombres de cada tiket (guardados en la carpeta data)
files <- list.files(path = "./data", pattern = ".txt", full.names = TRUE)

#Creamos una lista que contendrá cada ticket.
tickets <- list()

#Asignamos las líneas de los archivos .txt
for (file in files) {
  linea <- read_lines(file, locale = locale(encoding = 'latin1'))
  supermercado <- linea[1]
  direccion <- linea[2]
  ciudad <- linea[3]
  telefono <- linea[4]
  fecha <- linea[5]
  factura <- linea[6]
  indiceinicio <- grep("DESCRIPCIÓN", linea)
  indicefinal <- grep("TOTAL", linea)
  productos <- linea[indiceinicio + 1:indicefinal - 1]
  iVA_10_idx <- grep("10%", linea)
  iVA_21_idx <- grep("21%", linea)
  iVA_5_idx <- grep("\\b5%", linea) 
  candidatos_sinIVA_idx <- grep("\\b0,00\\b", linea)
  sinIVA_idx <- candidatos_sinIVA_idx[!grepl("PARKING", linea[candidatos_sinIVA_idx])]
  IVA <-linea[indicefinal+2 ]
  tarjetabancaria <- linea[indicefinal + 7]
  iVA_10_value <- ifelse(length(iVA_10_idx) > 0, linea[iVA_10_idx[1]], NA)
  iVA_21_value <- ifelse(length(iVA_21_idx) > 0, linea[iVA_21_idx[1]], NA)
  iVA_5_value <- ifelse(length(iVA_5_idx) > 0, linea[iVA_5_idx[1]], NA)
  sinIVA_value <- ifelse(length(sinIVA_idx) > 0, linea[sinIVA_idx[1]], NA)
#Creamos un data frame con los datos asignados
  datos <- data.frame(
    Supermercado = supermercado,
    Dirección = direccion,
    Ciudad = ciudad,
    Telefono = telefono,
    Fecha = fecha,
    Factura = factura,
    Iva_10 = iVA_10_value,
    Iva_21 = iVA_21_value,
    Iva_5 = iVA_5_value,
    SinIVA = sinIVA_value,
    IVA <- IVA,
    stringsAsFactors = FALSE
  )
  #Le asigno cada ticket a cada elemento de la lista
  tickets <- list.append(tickets, datos)
}

#Creamos un dataframe vacio donde añadiremos la información contenida en cada ticket.
datoscompletos <- data.frame()

#Le añadimos a cada columna del data frame un ticket.
for (tickets in tickets) {
  datoscompletos <- rbind(datoscompletos,tickets)
}

```

# Preguntas

Ahora que tenemos los tickets cargados correctamente en un data frame, nos planteamos las preguntas que queremos rresponder mediante el análisis exploratorio.

1.  ¿cuáles son los productos más comprados?

2.  ¿A qué hora se realizan más compras?

3.  ¿Qué método de pago es el más popular?

4.  ¿Cuáles son los productos menos comprados?
